// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "test": Application Controllers
//
// Command:
// $ goagen
// --design=github.com/bitlogic/gzipissue/design
// --out=$(GOPATH)/src/github.com/bitlogic/gzipissue
// --version=v1.2.0-dirty

package app

import (
	"github.com/goadesign/goa"
)

// initService sets up the service encoders, decoders and mux.
func initService(service *goa.Service) {
	// Setup encoders and decoders
	service.Encoder.Register(goa.NewJSONEncoder, "application/json")
	service.Encoder.Register(goa.NewGobEncoder, "application/gob", "application/x-gob")
	service.Encoder.Register(goa.NewXMLEncoder, "application/xml")
	service.Decoder.Register(goa.NewJSONDecoder, "application/json")
	service.Decoder.Register(goa.NewGobDecoder, "application/gob", "application/x-gob")
	service.Decoder.Register(goa.NewXMLDecoder, "application/xml")

	// Setup default encoder and decoder
	service.Encoder.Register(goa.NewJSONEncoder, "*/*")
	service.Decoder.Register(goa.NewJSONDecoder, "*/*")
}

// BadController is the controller interface for the Bad actions.
type BadController interface {
	goa.Muxer
	goa.FileServer
}

// MountBadController "mounts" a Bad resource controller on the given service.
func MountBadController(service *goa.Service, ctrl BadController) {
	initService(service)
	var h goa.Handler

	h = ctrl.FileHandler("/bad/*filepath", "./swagger")
	service.Mux.Handle("GET", "/bad/*filepath", ctrl.MuxHandler("serve", h, nil))
	service.LogInfo("mount", "ctrl", "Bad", "files", "./swagger", "route", "GET /bad/*filepath")

	h = ctrl.FileHandler("/bad/", "swagger/index.html")
	service.Mux.Handle("GET", "/bad/", ctrl.MuxHandler("serve", h, nil))
	service.LogInfo("mount", "ctrl", "Bad", "files", "swagger/index.html", "route", "GET /bad/")
}

// GoodController is the controller interface for the Good actions.
type GoodController interface {
	goa.Muxer
	goa.FileServer
}

// MountGoodController "mounts" a Good resource controller on the given service.
func MountGoodController(service *goa.Service, ctrl GoodController) {
	initService(service)
	var h goa.Handler

	h = ctrl.FileHandler("/good/*filepath", "./swagger")
	service.Mux.Handle("GET", "/good/*filepath", ctrl.MuxHandler("serve", h, nil))
	service.LogInfo("mount", "ctrl", "Good", "files", "./swagger", "route", "GET /good/*filepath")

	h = ctrl.FileHandler("/good/", "swagger/index.html")
	service.Mux.Handle("GET", "/good/", ctrl.MuxHandler("serve", h, nil))
	service.LogInfo("mount", "ctrl", "Good", "files", "swagger/index.html", "route", "GET /good/")
}
