// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "test": bad TestHelpers
//
// Command:
// $ goagen
// --design=github.com/bitlogic/gzipissue/design
// --out=$(GOPATH)/src/github.com/bitlogic/gzipissue
// --version=v1.2.0-dirty

package test
